---
#


# directories
- name: "data deposition directory existance"
  file: path="/deposit" state=directory

# lighttpd user created by package install; UID/GID does not need to sync
- name: "deposition request directory"
  file: path='/deposit/requests' state=directory owner=lighttpd group=lighttpd

- name: "deposition processed directory"
  file: path='/deposit/processed' state=directory

- name: "data hold directory existance"
  file: path="/hold" state=directory owner=sbgriddb group=sbgriddb


