# ubuntu 1604
- name: dependencies-u1604
  tags: dcm
  when: ( ansible_distribution == "Ubuntu" )
  apt: name={{ item }} state=present update_cache=true
  with_items:
   - redis-server
   - redis-tools
#   - python-redis

# centos 6
- name: dependencies-c6
  tags: dcm
  when: ( ansible_distribution == "CentOS" )
  yum: name={{ item }} state=present 
  with_items:
   - redis
#   - python-redis

- name: start redis
  tags: dcm
  service: name=redis state=started enabled=yes

